<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <SDL2DIR>SDL2-2.28.5</SDL2DIR>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup />
  <ItemGroup>
    <BuildMacro Include="SDL2DIR">
      <Value>$(SDL2DIR)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>